# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-02-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
